version: "3.0"
services:
  tedge:
   build: ./tedge
   hostname: tedge
   container_name: thin-edge.io
   expose:
      - "1883"
      - "8080"
   ports:
      - "1883:1883"
      - "8080:80"
   volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
   deploy:
      restart_policy:
         condition: on-failure
  node-red:
   image: nodered/node-red:latest
   hostname: node-red
   container_name: node-red
   expose:
      - "1880"
   ports:
      - "1880:1880"
   environment:
      - TZ=Europe/Amsterdam
   user: root:root
   volumes:
      - ./node-red/data:/data
   deploy:
      restart_policy:
        condition: on-failure
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
      - '53:53'
    volumes:
      - ./influx/data:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=changemeplease
      - DOCKER_INFLUXDB_INIT_ORG=SAG 
      - DOCKER_INFLUXDB_INIT_BUCKET=thin-edge.io
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Ubcnrs4eIes_UN-7L38TUKYcYSbFXrme8vsk9YoJVwWmPT25QObxRnl0dHvWogwXgyORBY9_ucqKuP1tFVySqA==
    deploy:
      restart_policy:
        condition: on-failure
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/config:/etc/telegraf
    environment: 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=changemeplease
      - DOCKER_INFLUXDB_INIT_ORG=SAG 
      - DOCKER_INFLUXDB_INIT_BUCKET=thin-edge.io
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Ubcnrs4eIes_UN-7L38TUKYcYSbFXrme8vsk9YoJVwWmPT25QObxRnl0dHvWogwXgyORBY9_ucqKuP1tFVySqA==
      - TELEGRAF_CONFIG_PATH=/etc/telegraf/telegraf.conf
    deploy:
      restart_policy:
        condition: on-failure
